// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hrvadl/book-service/internal/domain/book (interfaces: BookSaver)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_saver.go -package=mocks . BookSaver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	book "github.com/hrvadl/book-service/internal/domain/book"
	gomock "go.uber.org/mock/gomock"
)

// MockBookSaver is a mock of BookSaver interface.
type MockBookSaver struct {
	ctrl     *gomock.Controller
	recorder *MockBookSaverMockRecorder
}

// MockBookSaverMockRecorder is the mock recorder for MockBookSaver.
type MockBookSaverMockRecorder struct {
	mock *MockBookSaver
}

// NewMockBookSaver creates a new mock instance.
func NewMockBookSaver(ctrl *gomock.Controller) *MockBookSaver {
	mock := &MockBookSaver{ctrl: ctrl}
	mock.recorder = &MockBookSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookSaver) EXPECT() *MockBookSaverMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockBookSaver) Save(arg0 context.Context, arg1 book.Book) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockBookSaverMockRecorder) Save(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockBookSaver)(nil).Save), arg0, arg1)
}
